
import java.text.DecimalFormat;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author juanita
 */
public class Calculator_Rodriguez extends javax.swing.JFrame {
    // Purpose: Holds the total bunber
    double total;
    // Number Entered
    int numbersEnter;
    //Purpose: Creates a array to hold the numbers
    private int numbers[];
    private int size;
    // Constat Purpose: Total number allow
    static final int TOTAL_ENTRIES = 10;
    
    /**
     * Creates new form Calculator_Rodriguez
     */
    public Calculator_Rodriguez()
    {
        
        initComponents();
        // Will allocate the memory for 10 int
       numbers = new int[10];
       // start size to zero
       size = 0;
       
    }
             
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEnter = new javax.swing.JButton();
        JButtonReset = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonCalculate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListNumbers = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldEnterNumbers = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelMeanResult = new javax.swing.JLabel();
        jLabelDeviationResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jButtonEnter.setText("Enter");
        jButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterActionPerformed(evt);
            }
        });

        JButtonReset.setText("Reset");
        JButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonResetActionPerformed(evt);
            }
        });

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonCalculate.setText("Calculate");
        jButtonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("This Programs calculate the mean and the standard deviation:");

        jScrollPane1.setViewportView(jListNumbers);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Enter Numbers:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("The Mean is:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Standard Deviation:");

        jLabelMeanResult.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelMeanResult.setForeground(new java.awt.Color(0, 51, 255));

        jLabelDeviationResult.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDeviationResult.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelDeviationResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelMeanResult, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEnterNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButtonEnter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JButtonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCalculate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEnterNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEnter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCalculate)
                        .addGap(18, 18, 18)
                        .addComponent(JButtonReset)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExit))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMeanResult, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDeviationResult, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // Purpose: Allows the use to deside if they want to exit the application
        int exit = JOptionPane.showConfirmDialog(null, "Are you sure you want to Exit the System", "System Exit",
                JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE );
        if(exit == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
       
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void JButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonResetActionPerformed
       //Purpose:reset the size and allow the user to calculate
        // Author: Juana Rodriguez
        size = 0;
        //Purpose: Block some buttons so the user dont have access
        // and allos to use other
        // Author: Juana Rodriguez
        jButtonCalculate.setEnabled(false);
        JButtonReset.setEnabled(false);
        jLabelDeviationResult.setText(null);
        jLabelMeanResult.setText(null);       
        jTextFieldEnterNumbers.setText(null);
        jButtonEnter.setEnabled(true);
        jLabelDeviationResult.setVisible(false);
        jLabelMeanResult.setVisible(false);
        jTextFieldEnterNumbers.setEnabled(true);
        // Purpose Clear the Number Entered
        Number.clear();
        jListNumbers.setModel(Number);
    }//GEN-LAST:event_JButtonResetActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //Purpose: Block some buttons so the user dont have access
        // and allos to use other
        // Author: Juana Rodriguez        
        total = 0;
        numbersEnter = 0;
        jButtonCalculate.setEnabled(false);  
        JButtonReset.setEnabled(false);
        jLabelDeviationResult.setVisible(false);       
        jLabelMeanResult.setVisible(false);
       
       
    }//GEN-LAST:event_formWindowActivated
    //Author: Juana Rodriguez
    // Purpose:Created to Allow the user to enter only 10 number
    // block some buttons so the user do not use them
    DefaultListModel Number = new DefaultListModel();
    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
    try
    {   
    //Purpose: Create the array of the number
        //Author: Juana Rodriguez
        //data:9/5/2017
       numbers[size] = Integer.parseInt(jTextFieldEnterNumbers.getText());
       
       // Purpose: pass the array to the bariable num1 
       // Author: Juana Rodriguez
       // Date: 9/5/2017
       int num1 = numbers[size];
        // Purpose: increase 
       // Author: Juana Rodriguez
       // Date: 9/5/2017        
       size++;
       // Purpose: Add the elements to the List
       // Author: Juana Rodriguez
       // Date: 9/5/2017
       Number.addElement(num1);
       //Purpose: clear any existing colums and create new colums
       // Author: Juana Rodriguez
       // Date: 9/5/2017       
       jListNumbers.setModel(Number);
       //Purpose counts the size
       // Author: Juana Rodriguez
       // Date: 9/5/2017       
       total = total + num1;
       // Author: Juana Rodriguez
       // Date: 9/5/2017
       numbersEnter = numbersEnter + 1;
       // Purpose: passed the text 
       // Author: Juana Rodriguez
       // Date: 9/5/2017
       jTextFieldEnterNumbers.setText(null);
       // Purpose: Set the buttons 
       // Author: Juana Rodriguez
       // Date: 9/5/2017       
       jLabelMeanResult.setVisible(true);
       jLabelDeviationResult.setVisible(true);
       
       // Purpose: Get the dize of the number enter
       // Method name: getModel()/ getSize();
       // Author: Juana Rodriguez
       int count = jListNumbers.getModel().getSize();
       //Purpose: allows the user to enter only 10 numbers
       // Author: Juana Rodriguez
       if(count == TOTAL_ENTRIES)
       {
           // Purpose: Block some buttons for the user
           // Author: Juana Rodriguez
           jTextFieldEnterNumbers.setEnabled(false);
           jButtonEnter.setEnabled(false); 
           jButtonCalculate.setEnabled(true);
           
       }
    }
    // Purpose try catch block control of execution is passed to
    // the catch clock frem try block
    // Author: Juana Rodriguez
     catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Invalid Input. Try Again!!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_jButtonEnterActionPerformed

    private void jButtonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculateActionPerformed
       
        // Author: Juana Rodriguez
       // Date: 9/5/2017
       // Purpose: Call the class CalculationsClass
        CalculationsClass findinfo = new CalculationsClass();
        
        // Author: Juana Rodriguez
       // Date: 9/5/2017
       // Purpose: gets the SD, and mean from the class
        double SD = findinfo.getDeviation(numbers);
        double mean = findinfo.getMean(numbers);
        // DecimalFormat controls how many decimal places
        // will appear 
        DecimalFormat df = new DecimalFormat("#.##"); 
        //Purpose: Display the answer to the labels 
        // Author: Juana Rodriguez
        jLabelMeanResult.setText(df.format(mean)); 
        jLabelDeviationResult.setText(df.format(SD));
        
        // Makes the jButtonEnter enabled 
        jButtonEnter.setEnabled(false);
        JButtonReset.setEnabled(true);    
    }//GEN-LAST:event_jButtonCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator_Rodriguez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator_Rodriguez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator_Rodriguez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator_Rodriguez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator_Rodriguez().setVisible(true);
            }
        });
    }

    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonReset;
    private javax.swing.JButton jButtonCalculate;
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDeviationResult;
    private javax.swing.JLabel jLabelMeanResult;
    private javax.swing.JList<String> jListNumbers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldEnterNumbers;
    // End of variables declaration//GEN-END:variables
}

